#!/usr/bin/env python3
"""Pre-renders Noto Sans glyphs into 1-bit bitmaps for the Worker.

Workers have no font rasterizer, so text is blitted from these bitmaps.
Re-run after changing sizes or the character set:

    python3 scripts/bake_fonts.py > src/fonts.js
"""

import base64

from PIL import Image, ImageDraw, ImageFont

FONT_DIR = "/usr/share/fonts/noto"
TEXT = "".join(chr(c) for c in range(32, 127)) + "°éëèêïöüáóúàç–·"
DIGITS = "0123456789-°"

# name: (file, pixel size, characters)
FONTS = {
    "small": ("NotoSans-Regular.ttf", 20, TEXT),
    "body": ("NotoSans-Regular.ttf", 26, TEXT),
    "bodyBold": ("NotoSans-Bold.ttf", 26, TEXT),
    "title": ("NotoSans-Bold.ttf", 34, TEXT),
    "big": ("NotoSans-Bold.ttf", 44, TEXT),
    "huge": ("NotoSans-Bold.ttf", 150, DIGITS),
}


def bake(path, size, chars):
    font = ImageFont.truetype(f"{FONT_DIR}/{path}", size)
    ascent, descent = font.getmetrics()
    glyphs = {}
    for ch in chars:
        advance = round(font.getlength(ch))
        x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
        w, h = x1 - x0, y1 - y0
        if w <= 0 or h <= 0:
            glyphs[ch] = [advance, 0, 0, 0, 0, ""]
            continue
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
        bits = bytearray((w * h + 7) // 8)
        for i, v in enumerate(img.tobytes()):
            if v >= 128:
                bits[i >> 3] |= 0x80 >> (i & 7)
        glyphs[ch] = [advance, x0, y0, w, h, base64.b64encode(bits).decode()]
    return {"ascent": ascent, "descent": descent, "glyphs": glyphs}


def main():
    import json

    print("// Generated by scripts/bake_fonts.py from Noto Sans. Do not edit.")
    print("// glyph: [advance, xOffset, yOffsetFromBaseline, width, height, base64 1-bit rows]")
    for name, (path, size, chars) in FONTS.items():
        print(f"export const {name} = {json.dumps(bake(path, size, chars), ensure_ascii=False)};")


if __name__ == "__main__":
    main()
